### ISSUE TITLE
Suggestion: Get Environment Variable task

### ISSUE THREAD

**Issue by Wil73** [jessehouwing/azure-pipelines-variable-tasks#33]
The task.SetVariable operation available right now in TFS is only useful for custom Powershell tasks to pass values between each powershell task.

Right now i Have a custom powershell task (B) that generates a value.  I use task.SetVariable for that.  However when I need to use that variable in task (E) later on which is a third party task, the variable is not available to populate a task property.  It would be nice to have a task to read the environment variable from the agent machine into a build task and formally set the Build Variable on the server.

The variables we set in the build tasks themselves only travel one way: to the agent machine.  IF I create a variable on the agent machine it would be nice to pass that back to the build task on the server.

Great work Jesse! :D

- William

**Comment by jessehouwing** [comment]
I don't follow. If you set a variable in task A, it is available later on
in task B. If you're using step templates you may need to define the
variable at the build definition level, the value will be overwritten and
sent back by the agent.

**Comment by Wil73** [comment]
Hi Jesse.

What I am using is third party build tasks.  Red-Gate particularly.

[cid:image001.png@01D3AC01.63F98CC0]

I use TFS 2017

I have a custom powershell task: Generate Version Number – this sets an environment variable in the powershell $(Build.VersionNumber)

  Write-Host `n
  Write-Host "VersionNumber = $VersionNumber"
  Write-Host ("##vso[task.setvariable variable=Build_VersionNumber;]$VersionNumber")

I have a third party task Create DLM Nuget Package (from Red Gate) that requires that version number as a property of the task

[cid:image002.png@01D3AC01.63F98CC0]

It’s not possible to pass the environment variable back to be used by the third party task itself as a property.  I can use the enviornment variable in other custom powershell tasks, but not third party tasks.

I did try creating an emtpy varaible I the buid definition, but this actually overrides the environment variable such that it’s blank.  This only works if you do not set a build variable at all, and only for custom powershell tasks.

I have read other posts from other TFS users who have the same challenge.

Give it a try, the task.SetVariable feature only works for custom powershell tasks from what I have confirmed.  The build itself does not know about this variable from what I can tell.

w

**Comment by jessehouwing** [comment]
Can you add screenshot and logs?

Are you on agent version 1.x or 2.x?

**Comment by jessehouwing** [comment]
There are issues in some older agent versions when switching from
powershell to node type tasks and vice versa. So the exact agent version
may be important.

If that's the cause, then there is little I can do about it.

**Comment by Wil73** [comment]
I am on premise and using the most recent version of the agent for TFS 2017 update 2

2018-02-22T22:30:28.8816313Z ##[section]Starting: Build
2018-02-22T22:30:28.8816313Z Current agent version: '2.119.1'

w

**Comment by jessehouwing** [comment]
Hmmm rereading, do I understand that a task is setting an environment variable, butnus not using a log command or task.setvariabke to persist it...

So basically you'd want to have an option to make the input be read from a   build variable or an environment variable?

**Comment by Wil73** [comment]
I was hoping your variable manipulations task might resolve this, but it looks like I may have to find a different solution.

I have tested this with a variety of third party and built in tasks.  The only tasks that recognize variables set in custom powershell scripts are other custom powershell scripts.  At least those are the only passing test cases I have run into thus far.

You can see below I generate the version number in an early task, later I set the build number using anotehr custom power shell script just fine.  When I use a third party task and use the variable in the definition itself, its blank, unset.

I think the task.SetVariable only works for tasks that reference the environment variable in a powershell script. You may be right in that this may be node.js and not cooperating on account of that.

The log of generate version number is pretty sparse, even with debug set:

2018-02-22T22:27:15.9551946Z VersionNumber       = 18053.1727.16.30114
[cid:image004.png@01D3AC05.030353C0]2018-02-22T22:27:16.0019949Z
2018-02-22T22:27:16.0019949Z
2018-02-22T22:27:16.0019949Z VersionNumber = 18053.1727.16.30114
2018-02-22T22:27:16.0019949Z ##[debug]Processed: ##vso[task.setvariable variable=Build_VersionNumber;]18053.1727.16.30114
2018-02-22T22:27:16.0019949Z
2018-02-22T22:27:16.0019949Z
2018-02-22T22:27:16.0019949Z Revision Number = 30114
2018-02-22T22:27:16.0019949Z ##[debug]Processed: ##vso[task.setvariable variable=Build_RevisionNumber;]30114
2018-02-22T22:27:16.0019949Z
2018-02-22T22:27:16.0019949Z
2018-02-22T22:27:16.1579959Z ##[section]Finishing: Generate Version Number

But it does work since I use it to update the build number in my next task

        [cid:image004.png@01D3AC05.030353C0]


[cid:image001.png@01D3AC02.FBF55DF0]


The build definition is set to use this variable:

[cid:image004.png@01D3AC05.030353C0][cid:image003.png@01D3AC03.29A142F0]

I have the variables set as blank, but this turns up blank later as you will see

[cid:image005.png@01D3AC03.A942C100]

I print all environment vars to the screen

[cid:image004.png@01D3AC05.030353C0][cid:image007.png@01D3AC04.06C00310]

The third party task does not recognize the variable set in the powershell tasks before it.  This happens with any third party task I have tested thus far.

        [cid:image006.png@01D3AC05.030353C0]


2018-02-22T22:30:45.4801377Z ##[debug]Importing cmdlet 'Use-DlmDatabaseRelease'.
2018-02-22T22:30:45.5425381Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'packageVersion' because it is an empty string.
2018-02-22T22:30:45.5425381Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'packageVersion' because it is an empty string.
2018-02-22T22:30:45.5425381Z    at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
2018-02-22T22:30:45.5425381Z    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
2018-02-22T22:30:45.5425381Z    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2018-02-22T22:30:45.5581382Z --- End of stack trace from previous location where exception was thrown ---
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2018-02-22T22:30:45.5581382Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-22T22:30:45.5581382Z ##[debug]Leaving script DlmAutomationBuild.ps1
2018-02-22T22:30:45.5737383Z ##[error]PowerShell script completed with 1 errors.


w

**Comment by Wil73** [comment]
Ideally I woul like to be able to re-use the variable I set in custom power shell scripts I write (which does work), and in the build definition itself as a property value of a third party task.

Right now from my test cases this far only the former works.  The later always fails.

I hadn’t considered the nodejs factor as of yet.  You may be right I may have only tested nodejs based tasks possibly.  The half dozen third party/built-in tasks I tried all failed (including the Red Gate tasks).  I would have to confirm if they are all written in node js.

It almost looks like the variables set on the client don’t get passed back to TFS at all, and are only stored on the agent for that session.

This is how I store the variable.  And that does work and seems to be the right way that everyone uses:

  Write-Host `n
  Write-Host "VersionNumber = $VersionNumber"
  Write-Host ("##vso[task.setvariable variable=Build_VersionNumber;]$VersionNumber")

w

w

**Comment by jessehouwing** [comment]
The variables in the build definition itself are not overwritten. Someone
else has a task that does that. My tasks aren't intended to do that.

So only in the running build, the variable should be available. They're not
persisted at the end of the build.

The screenshots didn't come through. So I still don't fully understand it.
Are you available for a short Skype call?

On 22 Feb 2018 23:53, "Wil73" <notifications@github.com> wrote:

Ideally I woul like to be able to re-use the variable I set in custom power
shell scripts I write (which does work), and in the build definition itself
as a property value of a third party task.

Right now from my test cases this far only the former works. The later
always fails.

I hadn’t considered the nodejs factor as of yet. You may be right I may
have only tested nodejs based tasks possibly. The half dozen third
party/built-in tasks I tried all failed (including the Red Gate tasks). I
would have to confirm if they are all written in node js.

It almost looks like the variables set on the client don’t get passed back
to TFS at all, and are only stored on the agent for that session.

This is how I store the variable. And that does work and seems to be the
right way that everyone uses:

Write-Host `n
Write-Host "VersionNumber = $VersionNumber"
Write-Host ("##vso[task.setvariable
variable=Build_VersionNumber;]$VersionNumber")


w

w

**Comment by jessehouwing** [comment]
Now pushing a version that doesn't rely on the v1 powershell handler for Windows agents.

**Comment by jessehouwing** [comment]
If that doesn't fix it, I think you're looking for the "Set Variable" task that is packaged in this extension: https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-BuildUpdating-Tasks
